# Generated by Django 3.2.5 on 2022-03-14 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('max_seats', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
            ],
        ),
    ]
