# Generated by Django 3.2.5 on 2022-03-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_foodanddrinks_image'),
        ('waiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_start_date', models.DateTimeField(auto_now_add=True)),
                ('order_end_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('food_and_drinks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kitchen.foodanddrinks')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiters.tables')),
            ],
        ),
    ]
