# Generated by Django 3.2.5 on 2022-03-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='waiters.tables'),
        ),
    ]
