# Generated by Django 3.2.5 on 2022-03-17 15:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_categories_image'),
        ('waiters', '0003_alter_orders_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='food_and_drinks',
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('food_and_drinks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kitchen.foodanddrinks')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiters.orders')),
            ],
        ),
    ]
