# Generated by Django 3.2.5 on 2022-03-19 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waiters', '0004_auto_20220317_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='waiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.restaurantuser'),
            preserve_default=False,
        ),
    ]
