# Generated by Django 3.2.5 on 2022-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0005_orders_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
