# Generated by Django 3.2.5 on 2022-03-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0006_alter_orders_order_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
