# Generated by Django 3.2.5 on 2022-03-31 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import restaurant_project.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), restaurant_project.common.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), restaurant_project.common.validators.validate_only_letters])),
                ('picture', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.restaurantuser')),
            ],
        ),
    ]
