# Generated by Django 3.2.5 on 2022-03-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_categories_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['name']},
        ),
    ]
