# Generated by Django 3.2.5 on 2022-04-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_alter_ingredients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodanddrinks',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
