# Generated by Django 3.2.5 on 2022-04-05 15:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_alter_foodanddrinks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='foodanddrinks',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
