# Generated by Django 3.2.5 on 2022-04-16 07:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodanddrinks',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
